### ISSUE TITLE
Missing dataset

### ISSUE THREAD

**Issue by kennywalker** [nkrnrnk/BertPunc#1]
Would it be possible to include one of the datasets? It's difficult to tell the data format without an included dataset.

**Comment by tavanduy** [comment]
Hi @kennywalker. The datasets are most likely taken from here [https://github.com/IsaacChanghau/neural_sequence_labeling/tree/master/data/raw/LREC](url)

**Comment by kennywalker** [comment]
Thank you @tavanduy

**Comment by bharat-patidar** [comment]
Hi @tavanduy 

Thanks for sharing this dataset link, were you able to locate dataset mentioned in the updated code(train.py)?

I am trying to find NPR-podcasts dataset which is being loaded through following command:

`    data_train = load_file('data/NPR-podcasts/train')
`

@nkrnrnk

**Comment by JeremySun1224** [comment]
Maybe use this datasets: https://github.com/IsaacChanghau/neural_sequence_labeling/tree/master/data/raw/LREC
