### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by al-yakubovich** [nkrnrnk/BertPunc#2]
I tried to reproduce results using your Jupyter notebook but for some reasons, I got only:

  | COMMA | PERIOD | QUESTION | OVERALL
-- | -- | -- | -- | --
0.062041 | 0.063562 | 0.001647 | 0.042417
0.307018 | 0.231150 | 0.171429 | 0.236532
0.103223 | 0.099707 | 0.003264 | 0.068731

(for test2011asr)

Could you please tell me why the results are so bad?

**Comment by al-yakubovich** [comment]
For references, the code that I used:

```
import pandas as pd
import numpy as np
from glob import glob
from pytorch_pretrained_bert import BertTokenizer
import torch
from torch import nn
%matplotlib inline
import json
from tqdm import tqdm
from sklearn import metrics

from model import BertPunc
from data import load_file, preprocess_data, create_data_loader

path = 'models/20190418_211742/'
data_test_asr = load_file('data/LREC/test2011asr')
with open(path+'hyperparameters.json', 'r') as f:
    hyperparameters = json.load(f)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)

punctuation_enc = {
    'O': 0,
    'COMMA': 1,
    'PERIOD': 2,
    'QUESTION': 3
}

segment_size = hyperparameters['segment_size']
X_test_asr, y_test_asr = preprocess_data(data_test_asr, tokenizer, punctuation_enc, segment_size)

output_size = len(punctuation_enc)
dropout = hyperparameters['dropout']
bert_punc = BertPunc(segment_size, output_size, dropout)

batch_size = 1024
data_loader_test_asr = create_data_loader(X_test_asr, y_test_asr, False, batch_size)

def predictions(data_loader):
    y_pred = []
    y_true = []
    for inputs, labels in tqdm(data_loader, total=len(data_loader)):
        with torch.no_grad():
            inputs, labels = inputs, labels
            output = bert_punc(inputs)
            y_pred += list(output.argmax(dim=1).cpu().data.numpy().flatten())
            y_true += list(labels.cpu().data.numpy().flatten())
    return y_pred, y_true

y_pred_test, y_true_test = predictions(data_loader_test_asr)
eval_test = evaluation(y_pred_test, y_true_test)
eval_test
```

**Comment by kuldeepyadav** [comment]
Hi @al-yakubovich, I am trying to reproduce the results from this repository and having some challenges. Were you able to reproduce exact same results as reported in this repository?

**Comment by al-yakubovich** [comment]
Hi @kuldeepyadav. I was able to reproduce the reported results (at least very close to them). Make sure to run training before evaluation.

**Comment by k9luo** [comment]
Hi @al-yakubovich . I am trying to reproduce the results from this repo but having some trouble in loading the datasets. I am using the datasets from https://github.com/IsaacChanghau/neural_sequence_labeling/tree/master/data/raw/LREC. When I run train.py, [this line](https://github.com/nkrnrnk/BertPunc/blob/master/data.py#L8) complains about ```UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4086-4087: invalid continuation byte```. I have tried different ways of decoding the raw files and the datasets [here](https://github.com/IsaacChanghau/neural_sequence_labeling/tree/master/data/raw/LREC_converted). I was wondering if you had the same issue before and how you managed to load the datasets. Thank you!

**Comment by al-yakubovich** [comment]
Hi @k9luo!
Yes, I had such problem before. 
Try to use the following code to upload the data:
```
def load_file(filename):
    with open(filename, 'r', encoding="utf8", errors="ignore") as f:
        data = f.readlines()
    return data
```

**Comment by k9luo** [comment]
Hi @al-yakubovich ! Thank you very much for your reply. It solves my problem!

**Comment by NavKumarGit** [comment]
@al-yakubovich / @nkrnrnk - here the end goal of this model or this exercise to punctuate the given transcript or text which doesn't punctuation i.e. COMMA, PERIOD, QUESTIONMARK . 
Here there are method which trains the model on single word and even test like this only.
Is there any method which just returns prediction or predicted punctuated text of given unpunctuated text.\
Given input can be of 1 sentence or 1 page or 2 page, quite long , or we can say generated transcript of any YouTube video or audio speech.
Kindly help with this.

**Comment by JeremySun1224** [comment]
https://github.com/IsaacChanghau/neural_sequence_labeling/tree/master/data/raw/LREC

**Comment by JeremySun1224** [comment]
@k9luo maybe use GBK encoding
`def load_file(filename):
    with open(filename, 'r', encoding='gbk') as f:
        data = f.readlines()
    return data`

**Comment by JeremySun1224** [comment]
@k9luo maybe use GBK encoding, and it works on ```train2012 dataset```.
```
def load_file(filename):
    with open(filename, 'r', encoding='gbk') as f:
        data = f.readlines()
    return data
```

**Comment by k9luo** [comment]
@JeremySun1224 Thanks. I will give it a try!
